import type { AgentConfig } from "@/lib/types/agent";

// 4 default team members
export const DEFAULT_AGENTS: AgentConfig[] = [
  {
    id: "general_assistant",
    label: "General Assistant",
    description: "Your all-in-one AI assistant. Handles any question, task, or conversation that doesn't fit a specialist.",
    expertise: [
      "Answer any question across all domains",
      "Draft emails, messages, and quick documents",
      "Brainstorm ideas and organize thoughts",
      "Summarize articles, reports, and meeting notes",
      "Help with daily planning and decision making",
      "Translate between languages",
    ],
    avatar: "/pink.png",
    category: "productivity",
    promptFile: "general_assistant.txt",
    isDefault: true,
  },
  {
    id: "all_around_writer",
    label: "Content Writer",
    description: "Professional writer for articles, blogs, marketing copy, emails, and all forms of written content.",
    expertise: [
      "Blog posts, articles, and long-form content",
      "Marketing copy and ad text",
      "Email campaigns and newsletters",
      "Social media captions and threads",
      "Creative writing and storytelling",
      "Editing, proofreading, and tone adjustment",
    ],
    avatar: "/yellow.png",
    category: "writing",
    promptFile: "all_around_writer.txt",
    isDefault: true,
  },
  {
    id: "market_research_strategist",
    label: "Market Research",
    description: "Market research director who provides industry analysis, competitive intelligence, and strategic insights.",
    expertise: [
      "Market sizing and opportunity assessment (TAM/SAM/SOM)",
      "Competitive landscape analysis",
      "Consumer segmentation and persona building",
      "Industry trend forecasting",
      "Go-to-market strategy recommendations",
      "Survey design and data interpretation",
    ],
    avatar: "/blue.png",
    category: "research",
    promptFile: "market_research_strategist.txt",
    isDefault: true,
  },
  {
    id: "ppt_expert",
    label: "PPT Expert",
    description: "Presentation specialist who creates compelling slide decks, pitch decks, and visual storytelling.",
    expertise: [
      "Business presentations and pitch decks",
      "Data visualization and chart design",
      "Slide layout and visual hierarchy",
      "Presentation storytelling and narrative flow",
      "Executive summary slides",
      "Generate PPT files with python-pptx",
    ],
    avatar: "/green.png",
    category: "media",
    promptFile: "ppt_expert.txt",
    isDefault: true,
  },
];

// All 31 agents available in the marketplace
export const ALL_AGENTS: AgentConfig[] = [
  // --- Writing & Content ---
  {
    id: "all_around_writer",
    label: "Content Writer",
    description: "Professional writer for articles, blogs, marketing copy, and all forms of content.",
    expertise: ["Blog posts & articles", "Marketing copy", "Email campaigns", "Social media content", "Creative writing", "Editing & proofreading"],
    avatar: "/yellow.png",
    category: "writing",
    promptFile: "all_around_writer.txt",
  },
  {
    id: "academic_assistant_pro",
    label: "Academic Writer",
    description: "Academic writing expert for research papers, theses, literature reviews, and scholarly documents.",
    expertise: ["Research papers & theses", "Literature reviews", "Citation formatting (APA, MLA, Chicago)", "Abstract & methodology writing", "Academic editing & revision", "Grant proposals"],
    avatar: "",
    category: "writing",
    promptFile: "academic_assistant_pro.txt",
  },
  {
    id: "technical_writer",
    label: "Tech Writer",
    description: "Technical documentation specialist for API docs, user guides, and developer documentation.",
    expertise: ["API documentation", "User guides & manuals", "README & onboarding docs", "Release notes & changelogs", "Knowledge base articles", "Tutorial & how-to guides"],
    avatar: "",
    category: "writing",
    promptFile: "technical_writer.txt",
  },
  {
    id: "literature_professor",
    label: "Literary Analyst",
    description: "Literature professor for essay writing, literary analysis, and critical reading.",
    expertise: ["Literary analysis & criticism", "Essay structure & argumentation", "Comparative literature", "Poetry interpretation", "Book reviews", "Writing style coaching"],
    avatar: "",
    category: "writing",
    promptFile: "literature_professor.txt",
  },

  // --- Research & Analysis ---
  {
    id: "deep_research",
    label: "Deep Research",
    description: "Deep research agent that conducts thorough multi-source investigations and produces comprehensive reports.",
    expertise: ["Multi-source research (10+ sources)", "Fact verification & cross-referencing", "Structured report generation", "Industry & company deep dives", "Trend analysis", "Literature & data synthesis"],
    avatar: "",
    category: "research",
    promptFile: "deep_research.txt",
  },
  {
    id: "market_research_strategist",
    label: "Market Research",
    description: "Market research director for industry analysis, competitive intelligence, and GTM strategy.",
    expertise: ["Market sizing (TAM/SAM/SOM)", "Competitive analysis", "Consumer segmentation", "Trend forecasting", "Go-to-market strategy", "Survey design"],
    avatar: "/blue.png",
    category: "research",
    promptFile: "market_research_strategist.txt",
  },
  {
    id: "data_analysis",
    label: "Data Analyst",
    description: "Data analysis expert for spreadsheets, charts, A/B testing, and data-driven insights.",
    expertise: ["Excel & spreadsheet analysis", "Data visualization & charts", "A/B test analysis", "Cohort analysis", "Statistical summaries", "Dashboard & report design"],
    avatar: "",
    category: "research",
    promptFile: "data_analysis.txt",
  },

  // --- Finance & Investment ---
  {
    id: "financial_advisor",
    label: "Financial Advisor",
    description: "Personal financial advisor for budgeting, investment planning, tax strategy, and wealth management.",
    expertise: ["Personal budgeting & saving", "Investment portfolio strategy", "Tax planning basics", "Retirement planning", "Debt management", "Financial goal setting"],
    avatar: "",
    category: "finance",
    promptFile: "financial_advisor.txt",
  },
  {
    id: "investment_research_analyst",
    label: "Investment Research",
    description: "Equity research analyst for stock analysis, valuation models, and investment reports.",
    expertise: ["DCF & valuation modeling", "Company fundamental analysis", "Industry comparables", "Earnings analysis", "Risk assessment", "Investment memo writing"],
    avatar: "",
    category: "finance",
    promptFile: "investment_research_analyst.txt",
  },

  // --- Sales & Marketing ---
  {
    id: "brand_strategist",
    label: "Brand Strategy",
    description: "Brand strategist for positioning, visual identity, messaging frameworks, and brand audits.",
    expertise: ["Brand positioning & differentiation", "Visual identity guidelines", "Messaging architecture", "Brand audit & health check", "Naming & tagline creation", "Brand voice development"],
    avatar: "",
    category: "sales",
    promptFile: "brand_strategist.txt",
  },
  {
    id: "growth_hacker",
    label: "Growth Hacker",
    description: "Growth specialist for user acquisition, conversion optimization, and data-driven growth experiments.",
    expertise: ["Growth experiment design", "Funnel analysis & optimization", "User acquisition channels", "Retention & engagement tactics", "Viral loop design", "A/B testing strategy"],
    avatar: "",
    category: "sales",
    promptFile: "growth_hacker.txt",
  },
  {
    id: "sales_strategist",
    label: "Sales Strategy",
    description: "Sales strategist for pipeline management, deal negotiation, and revenue growth planning.",
    expertise: ["Sales process optimization", "Deal qualification (BANT/MEDDIC)", "Pipeline management", "Negotiation tactics", "Territory planning", "Sales enablement"],
    avatar: "",
    category: "sales",
    promptFile: "sales_strategist.txt",
  },

  // --- HR & Recruitment ---
  {
    id: "hr_talent_development",
    label: "HR & Talent",
    description: "HR leader for talent assessment, performance management, training, and organizational development.",
    expertise: ["Performance review frameworks", "Training & development programs", "Org design & culture building", "Compensation benchmarking", "Employee engagement", "DEI initiatives"],
    avatar: "",
    category: "hr",
    promptFile: "hr_talent_development.txt",
  },
  {
    id: "recruitment_strategist",
    label: "Recruiter",
    description: "Recruitment strategist for hiring pipeline design, job descriptions, and candidate evaluation.",
    expertise: ["Job description writing", "Interview question design", "Candidate scoring rubrics", "Hiring pipeline optimization", "Employer branding", "Offer negotiation guidance"],
    avatar: "",
    category: "hr",
    promptFile: "recruitment_strategist.txt",
  },
  {
    id: "community_manager",
    label: "Community Manager",
    description: "Community manager for online community building, engagement strategies, and user advocacy.",
    expertise: ["Community strategy & growth", "Engagement campaigns", "Content moderation guidelines", "Ambassador programs", "Event planning", "Community health metrics"],
    avatar: "",
    category: "hr",
    promptFile: "community_manager.txt",
  },

  // --- Legal ---
  {
    id: "legal_analyst",
    label: "Legal Analyst",
    description: "Legal analyst for contract review, compliance assessment, and legal research.",
    expertise: ["Contract review & redlining", "Compliance assessment", "Legal research (IRAC method)", "Privacy policy analysis (GDPR/CCPA)", "IP basics & trademark", "Risk identification"],
    avatar: "",
    category: "legal",
    promptFile: "legal_analyst.txt",
  },

  // --- Customer Service ---
  {
    id: "customer_support_agent",
    label: "Customer Support",
    description: "Customer support agent for ticket resolution, FAQ management, and customer communication.",
    expertise: ["Ticket triage & resolution", "FAQ & knowledge base creation", "Customer communication templates", "Escalation handling", "SLA management", "CSAT improvement"],
    avatar: "",
    category: "service",
    promptFile: "customer_support_agent.txt",
  },
  {
    id: "customer_success_strategist",
    label: "Customer Success",
    description: "Customer success strategist for retention, upselling, and customer health monitoring.",
    expertise: ["Customer health scoring", "Onboarding playbooks", "Churn prevention strategies", "Account expansion planning", "QBR preparation", "NPS & satisfaction analysis"],
    avatar: "",
    category: "service",
    promptFile: "customer_success_strategist.txt",
  },

  // --- Product & Operations ---
  {
    id: "product_manager",
    label: "Product Manager",
    description: "Product manager for requirements analysis, PRDs, roadmap planning, and feature prioritization.",
    expertise: ["Product Requirements Documents (PRD)", "Feature prioritization frameworks", "User story writing", "Roadmap planning", "Stakeholder management", "Competitive product analysis"],
    avatar: "",
    category: "product",
    promptFile: "product_manager.txt",
  },
  {
    id: "operations_manager",
    label: "Operations",
    description: "Operations manager for process optimization, efficiency improvement, and workflow design.",
    expertise: ["Process mapping & optimization", "Lean / Six Sigma methodology", "KPI design & tracking", "Vendor management", "SOP creation", "Cost reduction analysis"],
    avatar: "",
    category: "product",
    promptFile: "operations_manager.txt",
  },
  {
    id: "change_management_leader",
    label: "Change Management",
    description: "Change management leader for organizational transformation, stakeholder alignment, and adoption planning.",
    expertise: ["Change readiness assessment", "Stakeholder mapping & alignment", "Communication planning", "Training & adoption strategy", "Resistance management", "Post-change evaluation"],
    avatar: "",
    category: "product",
    promptFile: "change_management_leader.txt",
  },
  {
    id: "ux_research_specialist",
    label: "UX Research",
    description: "UX researcher for user interviews, usability testing, persona creation, and design insights.",
    expertise: ["User interview design & analysis", "Usability testing", "Persona & journey mapping", "Survey design", "Heuristic evaluation", "Design recommendation reports"],
    avatar: "",
    category: "product",
    promptFile: "ux_research_specialist.txt",
  },

  // --- Tech ---
  {
    id: "professional_coder",
    label: "Coding Assistant",
    description: "Programming assistant for writing code, debugging, learning to code, and technical problem-solving.",
    expertise: ["Write code in any language", "Debug errors & fix bugs", "Code explanation for beginners", "Algorithm & data structure help", "API integration guidance", "Best practices & code review"],
    avatar: "",
    category: "tech",
    promptFile: "professional_coder.txt",
  },
  {
    id: "sql_assistant",
    label: "SQL Expert",
    description: "SQL expert for writing queries, database design, and data extraction across all major databases.",
    expertise: ["SQL query writing & optimization", "Database schema design", "Data extraction & reporting", "Stored procedures & views", "Performance tuning", "Cross-dialect support (PostgreSQL, MySQL, etc.)"],
    avatar: "",
    category: "tech",
    promptFile: "sql_assistant.txt",
  },
  {
    id: "system_design",
    label: "System Design",
    description: "Systems architect for distributed system design, architecture decisions, and technical planning.",
    expertise: ["System architecture diagrams", "Scalability & reliability design", "Database selection & modeling", "API design patterns", "Microservices vs monolith decisions", "Performance & cost tradeoffs"],
    avatar: "",
    category: "tech",
    promptFile: "system_design.txt",
  },
  {
    id: "analytics_engineer",
    label: "Data Modeling",
    description: "Analytics engineer for data modeling, dbt, data warehousing, and BI pipeline design.",
    expertise: ["dbt model design", "Data warehouse architecture (Snowflake, BigQuery)", "ETL/ELT pipeline design", "Data quality & testing", "Metrics layer design", "BI dashboard planning"],
    avatar: "",
    category: "tech",
    promptFile: "analytics_engineer.txt",
  },

  // --- Education ---
  {
    id: "mr_ranedeer",
    label: "Tutor",
    description: "Personalized AI tutor that adapts to your learning style, pace, and goals across any subject.",
    expertise: ["Personalized curriculum planning", "Concept explanation at any level", "Practice exercises & quizzes", "Study schedule creation", "Learning progress tracking", "Multi-subject support"],
    avatar: "",
    category: "education",
    promptFile: "mr_ranedeer.txt",
  },

  // --- Translation ---
  {
    id: "pdf_translator",
    label: "Translator",
    description: "Translation assistant for documents, PDFs, and academic texts with formatting preservation.",
    expertise: ["PDF & document translation", "Academic paper translation", "Multi-language support", "Terminology consistency", "Format-preserving translation", "Technical & legal translation"],
    avatar: "",
    category: "productivity",
    promptFile: "pdf_translator.txt",
  },

  // --- Productivity ---
  {
    id: "productivity_assistant_gtd",
    label: "Productivity Coach",
    description: "GTD productivity coach for task management, weekly reviews, and personal effectiveness.",
    expertise: ["Getting Things Done (GTD) methodology", "Weekly review facilitation", "Project & task breakdown", "Priority matrix (Eisenhower)", "Time blocking strategies", "Habit tracking & accountability"],
    avatar: "",
    category: "productivity",
    promptFile: "productivity_assistant_gtd.txt",
  },

  // --- Media Generation ---
  {
    id: "image_generation",
    label: "Image Creator",
    description: "AI image generation specialist for creating photos, illustrations, and graphics via ChatGPT or Gemini.",
    expertise: ["Photorealistic image prompts", "Artistic & stylized imagery", "Product photography prompts", "Social media graphics", "Logo & icon concepts", "Platform optimization (ChatGPT / Gemini)"],
    avatar: "",
    category: "media",
    promptFile: "image_generation.txt",
  },
  {
    id: "video_generation",
    label: "Video Creator",
    description: "AI video generation specialist for creating clips via Runway, Kling, Veo, Sora, or Seedance.",
    expertise: ["Cinematic video prompts", "Commercial & product videos", "Social media reels & shorts", "Multi-shot storytelling", "Camera movement & lighting design", "Platform selection (Runway / Kling / Sora / Seedance)"],
    avatar: "",
    category: "media",
    promptFile: "video_generation.txt",
  },
  // ── Tier 1 new agents ──
  {
    id: "seo_specialist",
    label: "SEO Specialist",
    description: "Search engine optimization expert driving organic traffic through technical SEO, content strategy, and authority building.",
    expertise: ["Technical SEO audits and fix prioritization", "Keyword research and search intent mapping", "On-page optimization and content strategy", "Competitor SEO gap analysis", "Core Web Vitals and page speed optimization", "Link building and domain authority strategy"],
    avatar: "",
    category: "sales",
    promptFile: "seo_specialist.txt",
  },
  {
    id: "social_media_strategist",
    label: "Social Media Strategist",
    description: "Cross-platform social media strategist building engaged communities that drive business outcomes.",
    expertise: ["Platform-specific content strategy (Instagram, TikTok, LinkedIn, X)", "Content calendar planning and editorial workflow", "Community building and engagement tactics", "Social analytics and performance optimization", "Influencer collaboration strategy", "Organic and paid social integration"],
    avatar: "",
    category: "sales",
    promptFile: "social_media_strategist.txt",
  },
  {
    id: "devops_engineer",
    label: "DevOps Engineer",
    description: "CI/CD pipeline architect and infrastructure automation specialist for reliable, fast software delivery.",
    expertise: ["CI/CD pipeline design (GitHub Actions, GitLab CI, Jenkins)", "Docker containerization and Kubernetes orchestration", "Infrastructure-as-Code (Terraform, Pulumi, CloudFormation)", "Cloud infrastructure (AWS, GCP, Azure)", "Monitoring and observability (Prometheus, Grafana, Datadog)", "Deployment strategies (blue-green, canary, rolling)"],
    avatar: "",
    category: "tech",
    promptFile: "devops_engineer.txt",
  },
  {
    id: "security_engineer",
    label: "Security Engineer",
    description: "Application security specialist combining offensive security knowledge with practical defense and remediation.",
    expertise: ["Vulnerability assessment and penetration testing", "OWASP Top 10 and secure code review", "STRIDE threat modeling", "Authentication and authorization architecture", "Dependency and supply chain security", "Compliance frameworks (SOC2, GDPR, HIPAA)"],
    avatar: "",
    category: "tech",
    promptFile: "security_engineer.txt",
  },
  {
    id: "sales_coach",
    label: "Sales Coach",
    description: "Sales performance coach specializing in consultative selling, objection handling, and team skill development.",
    expertise: ["Discovery call coaching and qualification frameworks", "Objection handling scripts and role-play scenarios", "Sales methodology training (SPIN, Challenger, MEDDIC)", "Pipeline management and forecasting", "Negotiation tactics and closing techniques", "Sales email and outreach optimization"],
    avatar: "",
    category: "sales",
    promptFile: "sales_coach.txt",
  },
  {
    id: "proposal_strategist",
    label: "Proposal Strategist",
    description: "Proposal and RFP response specialist crafting compelling business proposals that win competitive bids.",
    expertise: ["Executive summary and win theme development", "RFP response management and compliance", "Competitive positioning and differentiation", "Pricing strategy and value presentation", "Case study and proof point integration", "Proposal structure and visual design guidance"],
    avatar: "",
    category: "sales",
    promptFile: "proposal_strategist.txt",
  },
  {
    id: "tax_strategist",
    label: "Tax Strategist",
    description: "Tax planning advisor for individuals and businesses, optimizing tax positions while maintaining compliance.",
    expertise: ["Personal and corporate tax planning", "Entity structure optimization (LLC, S-Corp, C-Corp)", "Deduction and credit identification", "Multi-jurisdiction tax strategy", "Retirement and wealth planning tax implications", "Tax compliance checklist and deadline management"],
    avatar: "",
    category: "finance",
    promptFile: "tax_strategist.txt",
  },
  {
    id: "accessibility_auditor",
    label: "Accessibility Auditor",
    description: "Web accessibility specialist ensuring digital products meet WCAG standards and serve all users.",
    expertise: ["WCAG 2.1/2.2 compliance auditing (A, AA, AAA)", "Screen reader and keyboard navigation testing", "Color contrast and visual accessibility", "ARIA implementation and semantic HTML review", "Form accessibility and error handling", "Accessibility remediation with code examples"],
    avatar: "",
    category: "tech",
    promptFile: "accessibility_auditor.txt",
  },
  {
    id: "podcast_strategist",
    label: "Podcast Strategist",
    description: "Podcast strategy and production expert helping launch, grow, and monetize podcasts.",
    expertise: ["Show concept development and positioning", "Episode structure and content calendar planning", "Guest booking strategy and outreach templates", "Production workflow (recording, editing, publishing)", "Audience growth and distribution tactics", "Monetization strategy (sponsorships, premium content)"],
    avatar: "",
    category: "sales",
    promptFile: "podcast_strategist.txt",
  },
  // ── Tier 2 agents ──
  {
    id: "linkedin_content_creator",
    label: "LinkedIn Creator",
    description: "LinkedIn content strategist building personal brands and thought leadership for professionals.",
    expertise: ["Personal brand positioning and content pillars", "High-engagement post formats (stories, carousels, polls)", "LinkedIn algorithm optimization and timing", "Professional networking and engagement strategy", "Thought leadership and authority building", "Content calendar for consistent visibility"],
    avatar: "",
    category: "sales",
    promptFile: "linkedin_content_creator.txt",
  },
  {
    id: "email_marketing_specialist",
    label: "Email Marketing",
    description: "Email marketing specialist designing lifecycle campaigns, automation sequences, and conversion optimization.",
    expertise: ["Welcome and onboarding email sequences", "Nurture and conversion campaign design", "Subject line optimization and A/B testing", "Automation workflow and trigger design", "List segmentation and personalization", "Deliverability and list hygiene best practices"],
    avatar: "",
    category: "sales",
    promptFile: "email_marketing_specialist.txt",
  },
  {
    id: "database_optimizer",
    label: "Database Optimizer",
    description: "Database performance engineer specializing in query optimization, index strategy, and scaling.",
    expertise: ["Query optimization with EXPLAIN ANALYZE", "Index strategy (B-tree, GIN, partial, covering)", "Schema design and normalization trade-offs", "Connection pooling and resource tuning", "Caching strategy (Redis, query cache, materialized views)", "Performance monitoring and regression detection"],
    avatar: "",
    category: "tech",
    promptFile: "database_optimizer.txt",
  },
  {
    id: "api_tester",
    label: "API Tester",
    description: "API testing specialist building comprehensive test strategies for REST, GraphQL, and gRPC APIs.",
    expertise: ["Functional test case design (happy path, edge cases, errors)", "Contract testing and API compatibility validation", "Performance testing (load, stress, spike)", "Security testing (auth, injection, rate limiting)", "Automated regression suites for CI/CD", "API documentation and spec validation"],
    avatar: "",
    category: "tech",
    promptFile: "api_tester.txt",
  },
  {
    id: "mobile_app_builder",
    label: "Mobile App Builder",
    description: "Cross-platform mobile developer building production-quality apps with React Native, Flutter, or native code.",
    expertise: ["React Native and Flutter development", "Native iOS (Swift) and Android (Kotlin) development", "Mobile UX and platform design guidelines", "Offline support and data synchronization", "Performance optimization (startup, animations, memory)", "App store submission and review guidelines"],
    avatar: "",
    category: "tech",
    promptFile: "mobile_app_builder.txt",
  },
  {
    id: "executive_summary_generator",
    label: "Executive Summary",
    description: "Executive communications specialist distilling complex information into decision-ready briefings.",
    expertise: ["BLUF (Bottom Line Up Front) executive summaries", "Board deck and investor update preparation", "Decision memos with options and trade-offs", "Cross-functional status report synthesis", "Stakeholder briefing and talking points", "Data-driven narrative for leadership audiences"],
    avatar: "",
    category: "productivity",
    promptFile: "executive_summary_generator.txt",
  },
  {
    id: "compliance_auditor",
    label: "Compliance Auditor",
    description: "Regulatory compliance specialist covering GDPR, SOC 2, HIPAA, and industry frameworks.",
    expertise: ["GDPR, SOC 2, HIPAA, PCI-DSS compliance assessment", "Gap analysis and remediation prioritization", "Policy and procedure template creation", "Data privacy impact assessments", "Vendor and third-party compliance evaluation", "Audit readiness and evidence collection"],
    avatar: "",
    category: "legal",
    promptFile: "compliance_auditor.txt",
  },
  // ── Tier 3 agents ──
  {
    id: "ui_designer",
    label: "UI Designer",
    description: "Visual interface designer creating beautiful, systematic UI with design tokens and component libraries.",
    expertise: ["Visual design systems and design tokens", "Color theory, typography scale, and spacing systems", "Component library design with all states and variants", "Responsive layout design across breakpoints", "Micro-interactions and transition specifications", "Design-to-development handoff documentation"],
    avatar: "",
    category: "product",
    promptFile: "ui_designer.txt",
  },
  {
    id: "data_visualization_specialist",
    label: "Data Visualization",
    description: "Data visualization specialist transforming complex datasets into clear, compelling visual stories.",
    expertise: ["Chart type selection based on data relationships", "Dashboard layout and visual hierarchy design", "Interactive visualization with D3.js and Plotly", "Colorblind-safe and accessible chart design", "Narrative-driven data presentation", "Python visualization (matplotlib, seaborn, Altair)"],
    avatar: "",
    category: "research",
    promptFile: "data_visualization_specialist.txt",
  },
  {
    id: "developer_advocate",
    label: "Developer Advocate",
    description: "Developer relations specialist building communities, documentation, and developer experience.",
    expertise: ["API documentation and quickstart guides", "Technical tutorials and code examples", "Developer community building and engagement", "Conference talks and workshop design", "Developer experience (DX) assessment", "Feedback loops between community and product"],
    avatar: "",
    category: "tech",
    promptFile: "developer_advocate.txt",
  },
  {
    id: "supply_chain_strategist",
    label: "Supply Chain Strategist",
    description: "Supply chain optimization consultant for procurement, logistics, and inventory management.",
    expertise: ["End-to-end supply chain mapping and optimization", "Inventory management and demand forecasting", "Supplier portfolio diversification and risk assessment", "Logistics network design and cost optimization", "Supply chain risk mitigation and contingency planning", "Sustainability and regulatory compliance in sourcing"],
    avatar: "",
    category: "product",
    promptFile: "supply_chain_strategist.txt",
  },
  {
    id: "corporate_training_designer",
    label: "Training Designer",
    description: "Corporate learning specialist designing training programs that drive measurable behavior change.",
    expertise: ["Training needs analysis and skills gap assessment", "Curriculum design using adult learning principles", "E-learning content creation (scenarios, simulations)", "Assessment design aligned with job performance", "Learning management system (LMS) strategy", "Training ROI measurement (Kirkpatrick model)"],
    avatar: "",
    category: "hr",
    promptFile: "corporate_training_designer.txt",
  },
  {
    id: "chief_of_staff",
    label: "Chief of Staff",
    description: "Executive operations specialist supporting C-suite with strategic planning and cross-functional coordination.",
    expertise: ["Strategic planning facilitation (OKRs, annual planning)", "Executive briefing and decision memo preparation", "Cross-functional initiative tracking and risk flagging", "Board deck and all-hands presentation support", "Operating cadence design (staff meetings, business reviews)", "Special project management and organizational change"],
    avatar: "",
    category: "productivity",
    promptFile: "chief_of_staff.txt",
  },
  {
    id: "incident_response_commander",
    label: "Incident Commander",
    description: "Production incident management specialist minimizing MTTR with structured response and blameless postmortems.",
    expertise: ["Incident severity classification (SEV1-4) and triage", "Incident command structure and role assignment", "Stakeholder communication templates and cadence", "Blameless post-mortem facilitation", "Runbook creation and maintenance", "SLO/SLI framework design and error budget policy"],
    avatar: "",
    category: "tech",
    promptFile: "incident_response_commander.txt",
  },
  {
    id: "git_workflow_master",
    label: "Git Workflow Master",
    description: "Version control architect designing branching strategies and merge workflows for development teams.",
    expertise: ["Branching strategies (trunk-based, Git Flow, GitHub Flow)", "Merge workflow design with quality gates", "Branch protection rules and CI/CD integration", "Commit conventions and semantic versioning", "Monorepo and multi-repo management", "Git migration and workflow transition planning"],
    avatar: "",
    category: "tech",
    promptFile: "git_workflow_master.txt",
  },
  {
    id: "rapid_prototyper",
    label: "Rapid Prototyper",
    description: "MVP and prototype specialist who takes ideas from concept to working demo at startup speed.",
    expertise: ["Hypothesis-driven MVP scoping", "Rapid tech stack selection (Next.js, Supabase, Vercel)", "Functional prototype with real data interactions", "User feedback collection mechanism design", "Technical debt documentation and migration path", "No-code/low-code tool integration when appropriate"],
    avatar: "",
    category: "tech",
    promptFile: "rapid_prototyper.txt",
  },
];

// Helper: get default agents
export function getDefaultAgents(): AgentConfig[] {
  return DEFAULT_AGENTS;
}

// Helper: get marketplace agents (exclude already hired ones)
export function getMarketplaceAgents(hiredIds: string[]): AgentConfig[] {
  return ALL_AGENTS.filter((a) => !hiredIds.includes(a.id));
}
