import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — YoBoss",
  description: "How YoBoss collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#F6F3EE]">
      <div className="max-w-3xl mx-auto px-6 pt-6 flex items-center justify-between">
        <Link href="/" className="text-xl font-bold tracking-tighter text-[#2B2B2B]">
          YoBoss
        </Link>
      </div>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold text-[#2B2B2B] mb-3">Privacy Policy</h1>
        <p className="text-sm text-[#9B948B] mb-10">Last updated: April 27, 2026</p>

        <div className="prose prose-sm max-w-none text-[#2B2B2B] space-y-6">
          <section>
            <h2 className="text-xl font-semibold text-[#2B2B2B]">1. What we collect</h2>
            <p>
              When you sign up we store the email address and (where provided) the name and avatar
              from your authentication provider. While you use YoBoss we store the goals, phases,
              tasks, notes, and chat messages you create. Anonymized usage telemetry (request
              counts, model tokens) is recorded for billing and quality monitoring.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#2B2B2B]">2. How we use it</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Operate the product — render your data back to you and run AI requests on your behalf.</li>
              <li>Bill subscriptions and credit purchases through Stripe.</li>
              <li>Send essential transactional email (auth confirmations, billing receipts).</li>
              <li>Investigate bugs and improve product quality. We never sell your data.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#2B2B2B]">3. Third-party processors</h2>
            <p>YoBoss runs on top of these services. Each receives only what it needs to do its job:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Supabase</strong> — database, authentication, file storage.</li>
              <li><strong>Anthropic</strong> — your chat content is sent to the Claude API to generate AI responses.</li>
              <li><strong>Stripe</strong> — payment processing for subscriptions and credits. We never see your card details.</li>
              <li><strong>Vercel</strong> — application hosting and edge runtime logs.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#2B2B2B]">4. Data retention</h2>
            <p>
              Your data persists for as long as your account is active. You may delete individual
              goals, tasks, and chat sessions from inside the app. To delete your account and all
              associated data, email us at the contact below — we will action the request within
              30 days.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#2B2B2B]">5. Files generated by AI</h2>
            <p>
              Files produced by AI code execution are held by Anthropic for a limited window
              (typically 30 days from creation) and then expire. Download what you want to keep
              long-term.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#2B2B2B]">6. Your rights</h2>
            <p>
              You can request access, correction, or deletion of your personal data at any time.
              You can export your goals and tasks via the app, or contact us for a full data
              export.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#2B2B2B]">7. Cookies</h2>
            <p>
              We use first-party cookies only — strictly necessary cookies for authentication
              (session tokens) and preference cookies (UI state). No advertising or tracking
              cookies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#2B2B2B]">8. Contact</h2>
            <p>
              Questions or requests about your data? Email{" "}
              <a href="mailto:contact@mail.yoboss.ai" className="text-[#7FAEE6] hover:underline">
                contact@mail.yoboss.ai
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
