import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/db/server";
import { getAnthropicClient } from "@/lib/ai/client";

// GET /api/ai/files/[fileId] — download a file generated by code execution
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ fileId: string }> }
) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { fileId } = await params;
  const client = getAnthropicClient();

  try {
    // Get file metadata
    const metadata = await client.beta.files.retrieveMetadata(fileId);

    // Download file content
    const downloadResponse = await client.beta.files.download(fileId);
    const fileBytes = Buffer.from(await downloadResponse.arrayBuffer());

    return new Response(fileBytes, {
      headers: {
        "Content-Type": metadata.mime_type || "application/octet-stream",
        "Content-Disposition": `attachment; filename="${metadata.filename || "download"}"`,
        "Content-Length": fileBytes.length.toString(),
      },
    });
  } catch (error) {
    console.error("File download error:", error);
    return NextResponse.json(
      { error: "Failed to download file" },
      { status: 500 }
    );
  }
}
