-- Phase tasks: per-phase sub-tasks (the 1.1, 1.2, 1.3, ... checklist items
-- that the AI generates inside each phase of the roadmap).
--
-- Mirrors the daily_tasks → weekly_plans relationship: phase_tasks is the
-- normalized child of phases. Each row is its own checkable task with its
-- own priority and ordering, so toggling completion is a single-row UPDATE
-- (no array-rewrite race conditions).
--
-- Replaces the previous design where these items were generated by the AI
-- but never persisted (and a separate "goal_todos" list overlapped with
-- them). Goal-level to-dos are removed in favor of putting all actionable
-- work under phases.

CREATE TABLE public.phase_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  phase_id uuid REFERENCES public.phases(id) ON DELETE CASCADE NOT NULL,
  title text NOT NULL,
  priority text DEFAULT 'medium' CHECK (priority IN ('high', 'medium', 'low')),
  completed boolean DEFAULT false NOT NULL,
  completed_at timestamptz,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.phase_tasks ENABLE ROW LEVEL SECURITY;

-- A user can CRUD a phase_task iff they own the parent phase's goal.
CREATE POLICY "Users can CRUD own phase tasks" ON public.phase_tasks FOR ALL
  USING (
    phase_id IN (
      SELECT phases.id FROM public.phases
      JOIN public.goals ON goals.id = phases.goal_id
      WHERE goals.user_id = auth.uid()
    )
  );

CREATE INDEX idx_phase_tasks_phase_id ON public.phase_tasks(phase_id);
CREATE INDEX idx_phase_tasks_phase_id_sort ON public.phase_tasks(phase_id, sort_order);
